version: '3.9'

networks:
  gringotts:

services:

  gringotts-core:
    build: .
    image: gringotts-core:latest
    container_name: gringotts-core
    restart: unless-stopped
    depends_on:
      - gringotts-db
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://gringotts-db:5432/gringotts
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-gringotts}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-gringotts}
      - IVARRACE_JWT_SECRET=${JWT_SECRET:-default}
    networks:
      - gringotts
          
  gringotts-db:
    image: 'postgres:13.1-alpine'
    container_name: gringotts-db
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-gringotts}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-gringotts}
      - POSTGRES_DB=gringotts
    networks:
      - gringotts