server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gringotts
    username: gringotts
    password: gringotts
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update #create-drop #update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

#Swagger config
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

#Auth jwt config
ivarrace:
  jwt:
    secret: "change-me"
    issuer: "ivarrace.com"