name: Build & Publish

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          # VPS IP
          host: ${{ secrets.VPS_SSH_HOST }}
          # VPS username
          username: ${{ secrets.VPS_SSH_USERNAME }}
          # SSH key (copy it from your local machine)
          key: ${{ secrets.VPS_SSH_SECRET }}
          # SSH port
          port: ${{ secrets.VPS_SSH_PORT }}
          # passphrase
          #passphrase: ${{ env.SSH_PASSPHRASE }}

          env:
            POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
            JWT_SECRET: ${{ secrets.JWT_SECRET }}

          script: |
            echo "Moveing to project path..."
            cd ${{ secrets.PROJECT_PATH }}
            echo "Pull GitHub repo..."
            git pull origin main
            echo "Stoping containers..."
            docker compose down
            echo "Building containers..."
            docker compose up --build -d --remove-orphans
            echo "Deleting old image(s)..."
            docker image prune -a -f
