name: Deploy on VPS

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          # VPS IP
          host: ${{ secrets.VPS_SSH_HOST }}
          # VPS username
          username: ${{ secrets.VPS_SSH_USERNAME }}
          # SSH key (copy it from your local machine)
          password: ${{ secrets.VPS_SSH_SECRET }}
          # SSH port
          port: ${{ secrets.VPS_SSH_PORT }}

          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull origin main
            docker compose down
            docker compose up --build -d --remove-orphans
            docker image prune -a -f
